### ISSUE TITLE
Compatibility Issues?

### ISSUE THREAD

**Issue by oneEyedSunday** [ogbanugot/forensicLog#1]
Hey there
I haven't tried this yet, but any particular compatibility issues on a mac?

**Comment by oneEyedSunday** [comment]
So the first line of the requirements.txt file should probably be removed. 
thats a global python declaration ainit.
and as feared `pywin224` which is defo incompatible with the MAC.
How do you run this on your ubuntu? you use a VM for this too? @ogbanugot

**Comment by ogbanugot** [comment]
The eventlog is for windows only. But the webcam facial recognition can work on any system. Apart from pywin32, every other requirement is cross platform. We can look at how to implement eventlog for Linux and Mac
